title: portfoilo
email: eugeneshikabli@gmail.com
url: https://github.com/shikabli/shikabli.github.io
description: "my portfolio site using jekyll."
# You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "jekyll,portfolio,software engineer"
skills: "Fullstack Developer - Backend Developer - Solution Architect"
meta_author: Shikabli Eugene

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
contact: static

# Credits content
credits: 'Miniport is a free to use, open source Bootstrap theme created by <a href="http://html5up.net">HTML5 UP</a>.'

